# - name: Render Terrfaorm files
#   template:
#     src: "{{ item }}"
#     dest: "{{ terraform_dir }}/{{ item }}"
#   with_items:
#     - main.tf
#     - variables.tf
#     - outputs.tf
#     - terraform.tfvars
#   tags:
#     - terraform

- name: Render Terraform Provider Configuration
  ansible.builtin.template:
    src: "{{template_dir}}/aws/provider.tf.j2"
    dest: "/tmp/provider.tf"
  register: provider_config

- name: Append Terraform Provider Configuration
  ansible.builtin.copy:
    content: "{{ lookup('file', '/tmp/provider.tf') }}"
    dest: "{{ terraform_dir }}/provider.tf"

- name: Delete Terraform Provider Configuration
  ansible.builtin.file:
    path: "/tmp/provider.tf"
    state: absent
