# playbook.yml
---
- hosts: localhost
  tasks:
    - name: Set environment variables as facts
      ansible.builtin.set_fact:
        USER_SPECIFIC_BUCKET_NAME: "tito"
        ENDPOINT: "ewr1.vultrobjects.com"
        VULTR_SECRET_KEY: "{{VULTR_SECRET_KEY}}"
        VULTR_ACCESS_KEY: "{{VULTR_ACCESS_KEY}}"
        access_key: "{{access_key}}"
        secret_key: "{{secret_key}}"
        vpcs: "{{vpcs|default([])}}"
        template_dir: "{{ playbook_dir }}/../../templates"

    - name: Set up dynamic roles
      ansible.builtin.set_fact:
        dynamic_roles: "{{dynamic_roles | default([])}}"
      loop: "{{dynamic_roles}}"

    - name: Include dynamic roles
      ansible.builtin.include_role:
        name: "{{item}}"
      loop: "{{dynamic_roles}}"
