# playbook.yml
---
- hosts: localhost
  vars:
    VULTR_ACCESS_KEY: "some shit goes here"
    VULTR_SECRET_KEY: "kdgjkgdslajglda"
    USER_SPECIFIC_BUCKET_NAME: "kjdflsdgklasga"
    ENDPOINT: "ndlkgngalksdngla"
    access_key: "gdklsajgkldajga"
    secret_key: "dnlkjgajlkdgja"
    generate_s3: true
    buckets: "{{buckets}}"
    dynamic_roles:
      - temp
      - provider
      - s3
  tasks:
    - name: Include dynamic roles
      ansible.builtin.include_role:
        name: "{{item}}"
      loop: "{{dynamic_roles}}"
