# playbook.yml
---
- hosts: localhost
  vars:
    VULTR_ACCESS_KEY: "{{VULTR_ACCESS_KEY}}"
    VULTR_SECRET_KEY: "{{VULTR_SECRET_KEY}}"
    USER_SPECIFIC_BUCKET_NAME: "tito"
    ENDPOINT: "ewr1.vultrobjects.com"
    access_key: "{{access_key}}"
    secret_key: "{{secret_key}}"
    generate_s3: true
    buckets: "{{buckets}}"
    dynamic_roles: "{{dynamic_roles}}}"

  tasks:
    - name: Set environment variables as facts
      set_fact:
        buckets: "{{buckets|default([])}}"
    - name: Set up dynamic roles
      set_fact:
        dynamic_roles: "{{dynamic_roles|default([]) + [item]}}"
      loop: "{{dynamic_roles}}"

    - name: Set Template Directory
      set_fact:
        template_dir: "{{ playbook_dir }}/../../templates"

    - name: Include dynamic roles
      ansible.builtin.include_role:
        name: "{{item}}"
      loop: "{{dynamic_roles}}"
