# playbook.yml
---
- hosts: localhost
  vars:
    VULTR_ACCESS_KEY: ""
    VULTR_SECRET_KEY: ""
    USER_SPECIFIC_BUCKET_NAME: "tito"
    ENDPOINT: "ewr1.vultrobjects.com"
    access_key: "AKIAVRRPZVJKWI47XO4E"
    secret_key: "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"
    generate_s3: true
    buckets: "{{buckets}}"
    dynamic_roles:
      - temp
      - provider
      - s3
  tasks:
    - name: Include dynamic roles
      ansible.builtin.include_role:
        name: "{{item}}"
      loop: "{{dynamic_roles}}"
