---
- name: Create Temporary Directory
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../../terraform/"
    state: directory
    mode: "0755"
    recurse: true
  tags:
    - terraform
  register: terraform_dir

# terraform_dir: "{{ playbook_dir }}/../../terraform/"
- name: Set Global Fact for Terraform Directory
  set_fact:
    terraform_dir: "{{ terraform_dir.path }}"
  tags:
    - terraform
