---
- name: Create S3 Buckets
  ansible.builtin.template:
    src: "{{template_dir}}/aws/buckets/main.tf.j2"
    dest: "/tmp/main.tf"
  register: template

- name: Create S3 Buckets
  ansible.builtin.copy:
    content: "{{ lookup('file', '/tmp/main.tf') }}"
    dest: "{{terraform_dir}}/main.tf"
