---
- name: Create S3 Buckets
  ansible.builtin.template:
    src: "{{template_dir}}/aws/buckets/main.tf.j2"
    dest: "/tmp/main.tf"
  register: template

- name: Create S3 Buckets
  ansible.builtin.blockinfile:
    path: "{{ terraform_dir }}/main.tf"
    block: "{{ lookup('file', '/tmp/main.tf') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
