---
- name: "S3 Configuration"
  ansible.builtin.template:
    src: "{{template_dir}}/aws/buckets/configuration.tf.j2"
    dest: "/tmp/configurations.tf"
  register: output

- name: "S3 Configuration"
  ansible.builtin.blockinfile:
    path: "{{terraform_dir}}/configurations.tf"
    block: "{{lookup('file', '/tmp/configurations.tf')}}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - S3 Configuration"
