---
- name: "S3 | Output"
  ansible.builtin.template:
    src: "{{template_dir}}/aws/buckets/output.tf.j2"
    dest: "/tmp/outputs.tf"
  register: output

- name: "S3 | Output | Write"
  ansible.builtin.blockinfile:
    block: "{{lookup('file', '/tmp/outputs.tf')}}"
    path: "{{terraform_dir}}/outputs.tf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{item}}"
