---
- name: "Create Policy"
  ansible.builtin.template:
    src: "{{template_dir}}/aws/buckets/policy.tf.j2"
    dest: "/tmp/policy.tf"
  register: output

- name: "Write Policy"
  ansible.builtin.blockinfile:
    block: "{{lookup('file', '/tmp/policy.tf')}}"
    path: "{{terraform_dir}}/policy.tf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{item}}"
